# Author: Hubertus Seitz
### Create Invoice Category
POST http://localhost:8080/invoice-categories
Accept: */*
Content-Type: application/json

{
  "name": "BeispielKategorie"
}

### Create Housing Object
POST http://localhost:8080/housing-objects
Accept: */*
Content-Type: application/json

{
  "name": "Sunset Apartments",
  "street": "123 Main St",
  "city": "Springfield",
  "state": "IL",
  "zipCode": "62704",
  "numberOfApartments": 2
}
