# Author: Hubertus Seitz
### Inform ProcessEngine about new Invoice | manual
POST http://localhost:8161/api/message/external-invoice-received?type=queue
Content-Type: application/xml
Authorization: Basic YWRtaW46YWRtaW4=

<?xml version="1.0" encoding="UTF-8"?>
<Document>
    <digitalInvoice>False</digitalInvoice>
</Document>



### Inform ProcessEngine about new Invoice | EDI
POST http://localhost:8161/api/message/external-invoice-received?type=queue
Content-Type: application/xml
Authorization: Basic YWRtaW46YWRtaW4=

<?xml version="1.0" encoding="UTF-8"?>
<Document>
    <Invoice>
        <InvoiceDate>2024-01-09</InvoiceDate>
        <InvoiceAmount>500</InvoiceAmount>
        <Description>Hausmeister Sachen</Description>
        <Status>Pending</Status>
        <Receiver>Hans Hausmeister</Receiver>
        <ReceiverIBAN>DE89370400440532013000</ReceiverIBAN>
        <ReceiverBIC>COBADEFFXXX</ReceiverBIC>
        <Currency>EUR</Currency>
        <ExternalInvoiceNumber>0815</ExternalInvoiceNumber>
    </Invoice>
    <digitalInvoice>True</digitalInvoice>
</Document>

