
### Inform ProcessEngine about new Invoice | manual
POST http://localhost:8161/api/message/invoice-received?type=queue
Content-Type: application/xml
Authorization: Basic YWRtaW46YWRtaW4=

<?xml version="1.0" encoding="UTF-8"?>
<Document>
    <digitalInvoice>False</digitalInvoice>
</Document>



### Inform ProcessEngine about new Invoice | EDI
POST http://localhost:8161/api/message/invoice-received?type=queue
Content-Type: application/xml
Authorization: Basic YWRtaW46YWRtaW4=

<?xml version="1.0" encoding="UTF-8"?>
<Document>
    <Invoice>
        <InvoiceDate>2025-01-09</InvoiceDate>
        <InvoiceAmount>1234.56</InvoiceAmount>
        <Description>Payment for services rendered</Description>
        <Status>Pending</Status>
        <Receiver>John Doe</Receiver>
        <ReceiverIBAN>DE89370400440532013000</ReceiverIBAN>
        <ReceiverBIC>COBADEFFXXX</ReceiverBIC>
        <ExternalInvoiceNumber>123456</ExternalInvoiceNumber>
    </Invoice>
    <digitalInvoice>True</digitalInvoice>
</Document>

